### PR TITLE
Fix incorrect amount for account balances

### LINKED ISSUE #4422: Balance of accounts shows incorrect amounts
## Problem Definition

image

## Logs

@kelsos said in discord that the reason is the ignored assets in this getter https://github.com/rotki/rotki/blob/d512cd408d5c83df54647cae3d820a2926055401/frontend/app/src/store/balances/getters.ts#L92

### System Description

Operating system: Linux
Rotki version: 1.24.0

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #4422

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

File: frontend/app/src/utils/calculation.ts [hunk 1]
```diff
@@ -1,9 +1,16 @@
...
+import { useIgnoredAssetsStore } from '@/store/assets';
 import { Zero } from '@/utils/bignumbers';
 
 export function assetSum(balances: { [asset: string]: Balance }) {
-  return Object.values(balances).reduce((sum, balance) => {
-    return sum.plus(balance.usdValue);
+  const { isAssetIgnored } = useIgnoredAssetsStore();
+
+  return Object.entries(balances).reduce((sum, [asset, balance]) => {
+    if (!isAssetIgnored || !get(isAssetIgnored(asset))) {
```
Comment (kelsos) [inline frontend/app/src/utils/calculation.ts:10]: Is there some condition can the `isAssetIgnored` be falsy?

Comment (lukicenturi) [reply frontend/app/src/utils/calculation.ts]: my bad, forgot to change it.

**Review by kelsos — APPROVED** [review]
lgtm :) thank you
