### PR TITLE
fix: dashboard balance search does not show ethereum tokens

### LINKED ISSUE #3896: Dashboard balance search does not show ethereum tokens
## Problem Definition

Trying to search in the dashboard search bar for any ethereum token shown there shows no results. If you search for something like ETH or BTC it shows, which I assume is probably due to searching by identifier and not symbol.

## Task

Fix it

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #3896

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- [ ] Dashboard balance search does not show ethereum tokens

### CODE REVIEW

File: frontend/app/src/store/balances/getters.ts [hunk 1]
```diff
@@ -642,26 +642,25 @@ export const getters: Getters<
...
-          for (const balance of nfb) {
-            if (balance.id === identifier) {
-              return {
-                identifier: balance.id,
-                symbol: balance.name,
-                name: balance.name,
-                assetType: 'ethereum_token'
-              } as SupportedAsset;
-            }
+  assetInfo: (state: BalanceState) => (identifier: string) => {
```
Comment (kelsos) [inline frontend/app/src/store/balances/getters.ts:645]: Was the problem that the destructured instance was on an old reference?

**Review by kelsos — APPROVED** [review]
lgtm, only rebase on top of bugfixes and change the target to bugfixes

File: frontend/app/src/store/balances/getters.ts (hunk 1 above)
Comment (lukicenturi) [reply frontend/app/src/store/balances/getters.ts]: Yes I guess. With destructuring, the supportedAssets will be `empty array` when searching.

**Review by yabirgb — APPROVED** [review]
seems to work fine. lgtm

**Comment by kelsos** [comment]
@lukicenturi It seems we are also missing the changelog entry here
