### PR TITLE
fix: add manual balance only fetch that particular asset price

### LINKED ISSUE #2817: Refreshing ethereum balances and adding newly detected token does not show price in dashboard
## Problem Definition

If a user has some ethereum tokens on the dashboard and had recently moved some new tokens to one of their ethereum accounts a hard-refresh of the ethereum balances is needed to see the new balance due to the 24 hrs cache of detected tokens.

After the refresh, the newly detected token seems to have a NaN price in the dashboard view.

Doing a "Refresh prices" fixes this. But I suppose a proper fix would be to see if new tokens are added and fetch their prices as they come.

## Task

Fix it.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #2817

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- Add manual balance only fetch that particular asset price, instead fetch all assets prices

### CODE REVIEW

File: frontend/app/src/components/dashboard/DashboardAssetTable.vue [hunk 1]
```diff
@@ -281,6 +281,7 @@ const DashboardAssetTable = defineComponent({
     };
 
     const calculatePercentage = (value: BigNumber, divider: BigNumber) => {
+      if (divider.isEqualTo(0)) return '0';
```
Comment (kelsos) [inline frontend/app/src/components/dashboard/DashboardAssetTable.vue:284]: `BigNumber.js` has also a `.isZero()` method that does the same

**Review by kelsos — APPROVED** [review]
lgtm, thank you
