### PR TITLE
fix: allow edit historic price in swap events

### LINKED ISSUE #10149: Swap events don't have a menu to edit the price
## Abstract

History events and evm events have the option to input a price for the asset. This is useful because it does the multiplication and shows you the value to ensure that no mistake was made. The feature is not available for swap events where you can't edit the historical price

## Specification

- Add a form to edit the historical price and update the historical prices endpoint when saving it

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #10149

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/docs/blob/main/usage-guides/index.md) to reflect the changes.

### CODE REVIEW

File: frontend/app/src/modules/history/management/forms/HistoryEventAssetPriceForm.vue [hunk 1]
```diff
@@ -24,19 +24,25 @@ interface HistoryEventAssetPriceFormProps {
   datetime: string;
   disableAsset?: boolean;
   v$: Validation;
+  noPriceFields?: boolean;
   hidePriceFields?: boolean;
   location: string | undefined;
+  disabled?: boolean;
+  amountFieldProps?: Record<string, any>;
+  assetFieldProps?: Record<string, any>;
```
Comment (kelsos) [inline frontend/app/src/modules/history/management/forms/HistoryEventAssetPriceForm.vue]: are these only for the data-cy attributes?

File: frontend/app/src/modules/history/management/forms/swap/SwapSubEventList.vue [hunk 2]
```diff
@@ -39,23 +41,58 @@ function remove(index: number) {
...
+
+const subEventRefs = ref<SwapSubEventRef[]>([]);
+
+function isSwapSubEventComponent(el: Element | ComponentPublicInstance | null): el is SwapSubEventRef {
+  return el !== null
+    && typeof el === 'object'
+    && '$el' in el
+    && 'submitPrice' in el
+    && typeof (el as any).submitPrice === 'function';
+}
```
Comment (kelsos) [inline frontend/app/src/modules/history/management/forms/swap/SwapSubEventList.vue]: There is not better way for this right? :cry:

File: frontend/app/src/modules/history/management/forms/swap/SwapSubEvent.vue [hunk 3]
```diff
@@ -149,48 +150,60 @@ watch(userNotes, (userNotes, oldUserNotes) => {
...
+          :v$="v$"
+          :location="location"
+          :amount-field-props="{
+            dataCy: `${type}-amount`,
+            label: amountLabel,
+          }"
+          :asset-field-props="{
+            dataCy: `${type}-asset`,
+            label: assetLabel,
+          }"
```
Comment (kelsos) [inline frontend/app/src/modules/history/management/forms/swap/SwapSubEvent.vue]: For the `data-cy` attributes, I’d still prefer to keep them as HTML attributes rather than passing them as props.

Can we do something like `:data-type="type"` on the component? Then internally we could construct attributes like `:data-cy="${$attrs['data-type']}-amount"` (or similar). Since these are primarily for testing, it’s better not to expose them as props.

As for the label:

Do we have a defined format or convention for labels? If so, we should align with that.

I was thinking it might make sense to generalize this kind of component. For example, we could use a translation key like:

```typescript
t('dual_component.amount', { label })
```

Where the translation string would be something like:

```json
"dual_component": {
  "amount": "{label} amount"
}
```

This way, we can just pass a single label when the prefix is the same for both the asset and the amount, keeping it more flexible and reusable.

**Comment by kelsos** [comment]
@lukicenturi when you deal with the edits can you please also add a change log entry?

File: frontend/app/src/modules/history/management/forms/swap/SwapSubEventList.vue (hunk 2 above)
Comment (lukicenturi) [reply frontend/app/src/modules/history/management/forms/swap/SwapSubEventList.vue]: sadly I don't see better way, either this, or using `as`
