### PR TITLE
fix: add guides for failed metamask integration

### LINKED ISSUE #4129: Import address from Metamask from non-default browser
## Abstract

When importing an address from Metamask to rotki, pressing Save directs you to the default browser. If Metamask is installed in a non-default browser, it becomes impossible to import it.

## Motivation

Metamask can only be installed in Firefox or Chrome. My default browser being Opera doesn't allow me to import my Metamask address. There seems to be no other way than to press Save, which gives you no choice of browser. 

## Specification

TBD

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #4129 

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

File: frontend/app/src/utils/metamask.ts [hunk 1]
```diff
@@ -26,10 +26,13 @@ export async function getMetamaskAddresses(): Promise<string[]> {
 
   assert(accountPermission);
 
-  const exposedAccounts = accountPermission.caveats.find(
-    caveat => caveat.name === 'exposedAccounts'
-  );
+  const addresses: string[] = [];
+  accountPermission.caveats.map(permission => {
```
Comment (kelsos) [inline frontend/app/src/utils/metamask.ts:30]: Since we are not using the result of the mapping here, we could replace map with a normal loop right?

**Review by kelsos — APPROVED** [review]
I only have a small comment but it looks good on my side.

@celkacelka should we make binaries or something to check if this approach actually solves the problem?

**Review by celkacelka — APPROVED** [review]
Works for me!
