### PR TITLE
fix: display only error text when merging assets

### LINKED ISSUE #6625: Improve how error message appears on merge assets form
## Problem Definition

image
Use vuelidate to parse the external messages and show the validation error to the proper field

## Tasks

- [ ] display only the message at the proper field

### PR DESCRIPTION
**Pull request by kelsos**
Closes #6625 
## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

File: frontend/app/src/components/asset-manager/MergeDialog.vue [hunk 1]
```diff
@@ -5,46 +5,47 @@ import { toMessages } from '@/utils/validation';
...
     set(done, true);
   } else {
-    set(errorMessages, [
-      ...get(errorMessages),
-      result.message ?? t('merge_dialog.error').toString()
-    ]);
+    set(
+      errorMessages,
+      typeof result.message === 'string'
+        ? { sourceIdentifier: result.message ?? t('merge_dialog.error') }
```
Comment (tewshi) [inline frontend/app/src/components/asset-manager/MergeDialog.vue:46]:
```typescript
result.message ?? t('merge_dialog.error')
```
since at this point, `result.message` is a string, then `?? t('merge_dialog.error')` will never run

because it will only run when `result.message` is `null` or `undefined`

perhaps `|| t('merge_dialog.error')`

Comment (kelsos) [reply frontend/app/src/components/asset-manager/MergeDialog.vue:46]: true good catch, let me change that
