### PR TITLE
Fixes issue with balances appearing zero

### LINKED ISSUE #1668: Force refreshing BTC balances removes all other assets from the frontend cached state
## Problem Definition

If the user refreshes BTC balances all other assets are removed from the frontend state. So only the refreshed BTC balances stay in the dashboard and the blockchain per account balances.

## Task

Fix it.

### LINKED ISSUE #1669: Many times BTC balances seem to be zero when the app starts
## Problem Definition

Sometimes when the application starts the BTC balances seem to be displayed as zero even if there is balance on the account. Refreshing the BTC balances may or may not fix it.

I experimented with an xpub account and it seems that the backend is queried correctly, response is returned with balance, but it is not displayed on the frontend.

@kelsos you need to take a look at this.

## Logs

Logs are not needed. This is a frontend problem.

### Task

Fix it

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1668 
Closes #1669

### CODE REVIEW

File: frontend/app/src/store/utils.ts [hunk 1]
```diff
@@ -36,3 +36,11 @@ export const setStatus: (
   };
   commit('setStatus', payload, { root: true });
 };
+
+export function isLoading(status: Status): boolean {
+  return (
+    status === Status.LOADING ||
+    status === Status.PARTIALLY_LOADED ||
+    status == Status.REFRESHING
```
Comment (LefterisJP) [inline frontend/app/src/store/utils.ts:44]: Why the differences in comparisons operators between this line and the two above?

**Review by LefterisJP — APPROVED** [review]
LGTM and seem to at least for the account I tested fix the problems.

But I have 1 code question.

File: frontend/app/src/store/utils.ts (hunk 1 above)
Comment (kelsos) [reply frontend/app/src/store/utils.ts:44]: Because I copy/pasted it and the last time I missed that :D nice catch :)
