### PR TITLE
Fixes defi deposit address suggestion

### LINKED ISSUE #3239: Update usable accounts for defi screen address selector
## Problem Definition

While splitting the MakerDAO DSR/MakerDAO Vaults I realized the getter responsible for providing all the addresses has not be updated in a while. This means that the addresses for the newer protocols are not returned.

While this is a bug since this requires a bit of refactoring I will put it in place for 1.20 since it requires a bit of work.

### PR DESCRIPTION
**Pull request by kelsos**
Closes #3239

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

File: frontend/start-dev.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ if (startDevProxy) {
 }
 
 process.stdout.write("Starting @rotki/common watch \n");
-const commonProcesses = spawn("npm run watch -w @rotki/common", {
+const commonProcesses = spawn("sleep 30 && npm run watch -w @rotki/common", {
```
Comment (yabirgb) [inline frontend/start-dev.js:38]: Why is this included in this PR?

**Review by yabirgb — APPROVED** [review]
flawless work. Thank you ser, only one question

File: frontend/start-dev.js (hunk 1 above)
Comment (kelsos) [reply frontend/start-dev.js:38]: because it wouldn't make sense to make a new PR only for that now would it? :P
There was a problem where without this the common watch will happen in parallel with the app-start and cause some build errors
