### PR TITLE
fix: on removing exchange, prevent fetching it's balances as it no longer exists

### LINKED ISSUE #7120: Removing an exchange's credentials should stop further queries
## Problem Definition

Iremoved bittrex credentials and 1-2 seconds later got an error message about the balance query failing due to the exchange not being registered.

## Logs

Looking at the logs, the removal of the credentials happens at 30:18

```
[16/12/2023 00:30:18 CET] DEBUG rotkehlchen.api.server Greenlet-1: start rotki api OPTIONS /api/1/exchanges view_args={}, query_string=b''
[16/12/2023 00:30:18 CET] DEBUG rotkehlchen.api.server Greenlet-1: end rotki api OPTIONS /api/1/exchanges view_args={}, query_string=b'', status_code=200, result=None
[16/12/2023 00:30:18 CET] DEBUG rotkehlchen.api.server Greenlet-1: start rotki api DELETE /api/1/exchanges view_args={}, query_string=b''
[16/12/2023 00:30:18 CET] DEBUG rotkehlchen.api.server Greenlet-1: end rotki api DELETE /api/1/exchanges view_args={}, query_string=b'', status_code=200, result={'result': True, 'message': ''}
```

Then some more logs follow ... and at 30:19 an async query to get bittrex's balances is made. And this seems to be made by the frontend?

```
[16/12/2023 00:30:19 CET] DEBUG rotkehlchen.api.server Greenlet-1: start rotki api GET /api/1/exchanges/balances/bittrex view_args={'location': 'bittrex'}, query_string=b'async_query=true'
[16/12/2023 00:30:19 CET] DEBUG rotkehlchen.api.server Greenlet-1: end rotki api GET /api/1/exchanges/balances/bittrex view_args={'location': 'bittrex'}, query_string=b'async_query=true', status_code=200, result={'result': {'task_id': 44}, 'message': ''}
```

which later down the line will fail due to the not registered error

```
[16/12/2023 00:30:20 CET] DEBUG rotkehlchen.api.server Greenlet-1: start rotki api GET /api/1/tasks view_args={}, query_string=b''
[16/12/2023 00:30:20 CET] DEBUG rotkehlchen.api.server Greenlet-1: end rotki api GET /api/1/tasks view_args={}, query_string=b'', status_code=200, result={'result': {'pending': [], 'completed': [44]}, 'message': ''}
[16/12/2023 00:30:20 CET] DEBUG rotkehlchen.api.server Greenlet-1: start rotki api GET /api/1/tasks/44 view_args={'task_id': 44}, query_string=b''
[16/12/2023 00:30:20 CET] DEBUG rotkehlchen.api.server Greenlet-1: end rotki api GET /api/1/tasks/44 view_args={'task_id': 44}, query_string=b'', status_code=200, result={'result': {'status': 'completed', 'outcome': {'result': None, 'message': 'Could not query balances for bittrex since it is not registered'}, 'status_code': 409}, 'message': ''}
```

### Task

Figure out why it happens and fix it.

### PR DESCRIPTION
**Pull request by tewshi**
Closes #7120 

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

File: frontend/app/src/store/exchanges/index.ts [hunk 1]
```diff
@@ -74,13 +74,6 @@ export const useExchangesStore = defineStore('exchanges', () => {
         delete balances[exchange.location];
         setConnectedExchanges(exchanges);
         set(exchangeBalances, balances);
-
-        if (exchanges.length > 0) {
-          await fetchExchangeBalances({
-            location: exchange.location,
-            ignoreCache: false
-          });
-        }
```
Comment (kelsos) [inline frontend/app/src/store/exchanges/index.ts:83]: @lukicenturi do you remember why this line was added?

**Review by kelsos — APPROVED** [review]
