### PR TITLE
fix: resolve some testing bugs in frontend

### LINKED ISSUE #4939: Add dark-mode specific version for icons that need it
## Problem Definition

Some icons are currently not shown well in dark mode. This problem is addressed already for some icons in the frontend in dark mode but not for all.

Apply the same methodology on all icons.

## Task

- Run through the app in dark mode and spot icons which need adjustment in dark mode.
- Adjust them

The icons we know so far that do are:

- Saddle logo (used in the oracles settings)
- Manual price oracle icon

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #4939

## Checklist

- [x] Show warning when currency rate is Zero
- [x] Fix loopring that wasn't being called.
- [x] Put asset icon placeholder with mdi-icon
- [x] Fix error queried address with ENS https://discord.com/channels/657906918408585217/683245846070165504/1028693011086983209
- [x] Fix location selector not being disabled when editing manual balances.
- [x] Fix ETH address book form didn't validate eth address.
- [x] Improve oracle source icon in dark mode https://github.com/rotki/rotki/issues/4939
- [x] Fix error when editing ETH token
```
Fails with {"message":"{\"token\": {\"type\": [\"Unknown field.\"]}}","result":null}
```

### CODE REVIEW

File: frontend/app/src/components/dashboard/BlockchainBalanceCardList.vue [hunk 1]
```diff
@@ -102,16 +102,24 @@ const loading = computed<boolean>(() => {
...
-    filter: grayscale(0);
+    &__item {
+      &:hover {
+        .blockchain-balance-box {
+          &__icon {
+            filter: grayscale(0);
+          }
+        }
+      }
+    }
```
Comment (kelsos) [inline frontend/app/src/components/dashboard/BlockchainBalanceCardList.vue:122]: Is there any reason we need `deep` here? 
From what I remember we use deep to affect global classes

Comment (lukicenturi) [reply frontend/app/src/components/dashboard/BlockchainBalanceCardList.vue:122]: I want it to also affect the blockchain balances details (Loopring etc)

Comment (kelsos) [reply frontend/app/src/components/dashboard/BlockchainBalanceCardList.vue:122]: OK but ideally since we control both components we could actually add rules to that component too instead of using `deep` couldn't we?
