### PR TITLE
fix: disable pnl report if event hasn't been queried recently

### LINKED ISSUE #10693: PnL Report temporary improvement
It can take too long for PnL report to be generated. Sometimes the issue is the user hasn't finished the history events querying, so it appears that the PnL report is stuck.

1 thing we can do is, we need to check if the history events processing is done, otherwise, we need to redirect user from PnL report generation to the history events and tell them to finish it first.

Also if it has been too long since they last query the history event, do it for them!

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #10693

### CODE REVIEW

File: frontend/app/src/components/profitloss/ReportGenerator.vue [hunk 1]
```diff
@@ -11,22 +17,71 @@ const emit = defineEmits<{
...
+  if (hasExchangesAccounts && exchangesLastQueriedTs > 0) {
+    const exchangesLastQueriedMs = exchangesLastQueriedTs * 1000;
+    if (now - exchangesLastQueriedMs >= minOutOfSyncMs) {
+      return true;
+    }
+  }
+
+  // Also consider it out of sync if never queried
+  return (hasEvmAccounts && evmLastQueriedTs === 0) || (hasExchangesAccounts && exchangesLastQueriedTs === 0);
+});
```
Comment (kelsos) [inline frontend/app/src/components/profitloss/ReportGenerator.vue]: How much overlap is there between this computed and the checks we do in the HistoryQueryIndicator.vue?

Would it be possible to move the common building blocks into a composable that we can re-use between the two of them?

**Comment by lukicenturi** [comment]
@kelsos this one can be checked again
