### PR TITLE
fix: another improvement in frontend

### LINKED ISSUE #4935: Differentiating between rate limiting and true failure to find historical price
## Abstract

At the moment when a price fails to be found during historical price queries in the PnL report there is no way to say the difference as a user apart from checking the logs.

We need a way to differentiate this and allow the user at the end of the PnL report to requery the oracle for the historical price if it was simply failing due to rate limiting.

### Backend

- In the backend where we catch the no price found error (https://github.com/rotki/rotki/blob/0ff02efb4ebc5d50501c773c3001373cdd3b444e/rotkehlchen/accounting/accountant.py#L167) differentiate between prices not found because of total failure in all oracles or if any oracle had a rate limiting.
- Modify the `MissingPrice` structure to also include information for rate limiting or not

### Frontend

At the end of the PnL report where we show to the user all the missing prices, take advantage of the extra information the backend now sends.

1. If there was no rate limiting keep the current behavior where the user is prompted to add a manual price
2. If there was rate limiting along with the manual price option allow an option to query the historical price api endpoint for the asset, at the given timestamp again. Process the result. If it's a failure again, fallback to only giving (1). I fit was succesfull then consider the item closed since at next PnL report the historical price should be saved in the DB cache.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #4935

## Checklist

- [x] Show error when add / edit transaction event
- [x] Fix this from yabir
image

- [x] Feat: https://github.com/rotki/rotki/issues/4935
- [x] Fix error cannot add xpub
- [x] Fix totalsState usdValue not updated when refresh prices
- [x] Prevent infinite asset fetching given unknown identifier. 
- [x] Fix about section not opened in docker.

### CODE REVIEW

File: frontend/app/src/components/PinnedSidebar.vue [hunk 1]
```diff
@@ -10,11 +10,19 @@
...
+        v-if="pinned && component"
+        v-bind="pinned.props"
+      />
     </div>
   </v-navigation-drawer>
 </template>
 <script setup lang="ts">
+// @ts-ignore
+// eslint-disable-next-line @typescript-eslint/no-unused-vars
+import { ComputedRef, VueConstructor } from 'vue';
```
Comment (kelsos) [inline frontend/app/src/components/PinnedSidebar.vue:24]: What happens if you don't import the VueConstructor?

File: frontend/app/src/components/About.vue [hunk 2]
```diff
@@ -35,12 +35,23 @@
...
+                        </div>
+                      </template>
+                      <span :class="css.directory">
+                        {{ dataDirectory }}
+                      </span>
+                    </v-tooltip>
                     <v-spacer />
                     <div v-if="isPackaged" class="ml-2">
-                      <v-tooltip top open-delay="400">
+                      <v-tooltip top>
```
Comment (kelsos) [inline frontend/app/src/components/About.vue:54]: Is there any reason the open-delay is removed from the tooltip?

Please keep the open delay at 400 ms in tooltips, otherwise, the tooltip will open even if you scroll over the element by accident which can be really annoying.

File: frontend/app/src/components/About.vue [hunk 3]
```diff
@@ -35,12 +35,23 @@
                 </td>
                 <td>
                   <div class="d-flex flex-row">
-                    <div class="text-truncate" :class="css.directory">
-                      {{ dataDirectory }}
-                    </div>
+                    <v-tooltip top>
```
Comment (kelsos) [inline frontend/app/src/components/About.vue:38]: Also add a open-delay here

File: frontend/app/src/components/accounts/AccountBalanceTable.vue [hunk 4]
```diff
@@ -596,6 +596,21 @@ const liabilities = (address: string) => {
...
+  );
+
+  if (index >= 0) {
+    get(collapsedXpubs).splice(index, 1);
+  }
+};
+
+defineExpose({
+  removeCollapsed
+});
```
Comment (kelsos) [inline frontend/app/src/components/accounts/AccountBalanceTable.vue:613]: Is this something that we broke when moving to composition? how did it work before?

File: frontend/app/src/components/accounts/AccountBalances.vue [hunk 5]
```diff
@@ -181,6 +181,8 @@ const deleteAccount = async () => {
     set(xpubToDelete, null);
     await deleteXpub(payload);
     get(balanceTable)?.removeCollapsed(payload);
+
+    await refreshAccounts(get(blockchain));
```
Comment (kelsos) [inline frontend/app/src/components/accounts/AccountBalances.vue:185]: any chance we can make `refreshAccounts` receive a `MaybeRef` and handle the get inside?

File: frontend/app/src/components/dashboard/EditBalancesSnapshotTable.vue [hunk 6]
```diff
@@ -475,7 +475,7 @@ const tableContainer = computed(() => {
 <style module lang="scss">
 .table {
   scroll-behavior: smooth;
-  max-height: calc(100vh - 310px);
+  max-height: calc(100vh - 340px);
   overflow: auto;
 }
```
Comment (kelsos) [inline frontend/app/src/components/dashboard/EditBalancesSnapshotTable.vue:480]: I see 3 different components having the exact same CSS class and the same change, maybe it would make more sense if it was extracted to an scss file and imported.

File: frontend/app/src/components/eth-address-book-manager/EthAddressBookManagement.vue [hunk 7]
```diff
@@ -112,129 +109,102 @@ import {
...
-    );
-
-    const onSearchTermChange = (term: string) => {
-      set(pendingSearch, term);
-      if (get(isTimeoutPending)) {
-        stop();
-      }
-      start();
-    };
+const location = computed<EthAddressBookLocation>(() => {
```
Comment (kelsos) [inline frontend/app/src/components/eth-address-book-manager/EthAddressBookManagement.vue:119]: Check the warning above, maybe in the template's v-for we can change the name from location to something else

File: frontend/app/src/components/history/transactions/TransactionContent.vue [hunk 8]
```diff
@@ -73,15 +73,9 @@
...
       >
-        <template #item.ignoredInAccounting="{ item, isMobile }">
+        <template #item.ignoredInAccounting="{ item }">
           <div v-if="item.ignoredInAccounting" class="pl-4">
-            <badge-display v-if="isMobile" color="grey">
-              <v-icon small> mdi-eye-off </v-icon>
-              <span class="ml-2">
-                {{ tc('common.ignored_in_accounting') }}
-              </span>
-            </badge-display>
```
Comment (kelsos) [inline frontend/app/src/components/history/transactions/TransactionContent.vue:83]: How does this look on mobile now? is there any reason for the removal?

File: frontend/app/src/components/profitloss/ReportMissingAcquisitions.vue [hunk 9]
```diff
@@ -185,7 +185,7 @@ const childHeaders = computed<DataTableHeader[]>(() => {
 <style module lang="scss">
 .table {
   scroll-behavior: smooth;
-  max-height: calc(100vh - 310px);
+  max-height: calc(100vh - 340px);
   overflow: auto;
```
Comment (kelsos) [inline frontend/app/src/components/profitloss/ReportMissingAcquisitions.vue:189]: this part looks like the others maybe it makes more sense o unify them than changing 4 different components

File: frontend/app/src/components/price-manager/latest/LatestPriceTable.vue [hunk 10]
```diff
@@ -204,17 +203,10 @@ const filteredPrices = computed(() => {
...
-    return {
-      ...item,
-      usdPrice: (assetPrice
-        ? assetPrice.multipliedBy(item.price)
-        : NoPrice) as BigNumber
-    };
-  });
+  return data.map(item => ({
+    ...item,
+    usdPrice: getAssetPrice(item.fromAsset)
```
Comment (kelsos) [inline frontend/app/src/components/price-manager/latest/LatestPriceTable.vue:208]: Is there any reason why the `item.toAsset` now seems to be `item.fromAsset`? was this a bug?

File: frontend/app/src/components/history/TransactionEventForm.vue [hunk 11]
```diff
@@ -223,326 +224,280 @@ import { bigNumberifyFromRef, One, Zero } from '@/utils/bignumbers';
...
+    type: Function as PropType<
+      (
+        event: NewEthTransactionEvent | EthTransactionEventEntry
+      ) => Promise<ActionStatus>
+    >
+  }
+});
 
-    const input = (valid: boolean) => emit('input', valid);
+const emit = defineEmits(['input']);
```
Comment (kelsos) [inline frontend/app/src/components/history/TransactionEventForm.vue:249]: It would be better to properly type the emitted events for type-checking.

It would be better to avoid the array syntax and use the proper typed syntax `defineEmits<{(e: 'input', valid: boolean):void}>()`

File: frontend/app/src/components/history/TransactionEventForm.vue [hunk 12]
```diff
@@ -223,326 +224,280 @@ import { bigNumberifyFromRef, One, Zero } from '@/utils/bignumbers';
...
+  (v: string) =>
+    !!v ||
+    t('transactions.events.form.event_type.validation.non_empty').toString()
+];
+
+const eventSubtypeRules = [
+  (v: string) =>
+    !!v ||
+    t('transactions.events.form.event_subtype.validation.non_empty').toString()
+];
```
Comment (kelsos) [inline frontend/app/src/components/history/TransactionEventForm.vue:322]: Since you are already migrating the component maybe also do the vuelidate treatment?

File: frontend/app/src/locales/de.json [hunk 13]
```diff
@@ -4,7 +4,8 @@
     "history": "Aave Verlauf"
   },
   "about": {
-    "copy_tooltip": "Programminformationen kopieren",
+    "copy_data_directory_tooltip": "Copy data directory",
```
Comment (kelsos) [inline frontend/app/src/locales/de.json:7]:
```suggestion
    "copy_data_directory_tooltip": "Datenverzeichnis kopieren",
```

File: frontend/app/src/locales/en.json [hunk 14]
```diff
@@ -3715,6 +3719,7 @@
       "gas_limit": "Gas Limit",
       "gas_price": "Gas Price",
       "gas_used": "Gas Used",
+      "gwei": "Gwei",
```
Comment (kelsos) [inline frontend/app/src/locales/en.json:3722]: Was there any reason Gwei was extracted? It is not really translatable.

File: frontend/app/src/locales/gr.json [hunk 15]
```diff
@@ -4,7 +4,8 @@
     "history": "Ιστορικό Aave"
   },
   "about": {
-    "copy_tooltip": "Αντιγραφή τών πληροφοριών της εφαρμογής",
+    "copy_data_directory_tooltip": "Copy data directory",
```
Comment (kelsos) [inline frontend/app/src/locales/gr.json:7]:
```suggestion
    "copy_data_directory_tooltip": "Αντιγραφή καταλόγου δεδομένων",
```

File: frontend/app/src/locales/en.json (hunk 14 above)
Comment (lukicenturi) [reply frontend/app/src/locales/en.json:3722]: So i think I should make const in that component with that string. Previously we put "gwei" as asset in <amount-input />, and it become error because no identifier found.

File: frontend/app/src/store/assets/retrieval.ts [hunk 16]
```diff
@@ -43,7 +43,7 @@ export const useAssetInfoRetrieval = defineStore(
         const address = getAddressFromEvmIdentifier(id);
         return `EVM Token: ${address}`;
       }
-      return '';
+      return id;
```
Comment (kelsos) [inline frontend/app/src/store/assets/retrieval.ts:46]: when does this happen? (ideally we should never show raw identifiers to the user)

File: frontend/app/src/store/assets/asset-cache.ts [hunk 17]
```diff
@@ -66,6 +66,9 @@ export const useAssetCacheStore = defineStore('assets/cache', () => {
         logger.debug(`unknown key: ${key}`);
         unknown.set(key, Date.now() + CACHE_EXPIRY);
       }
+    } catch (e) {
+      logger.debug(`unknown key: ${key}`);
+      unknown.set(key, Date.now() + CACHE_EXPIRY);
```
Comment (kelsos) [inline frontend/app/src/store/assets/asset-cache.ts:71]: In which case do we have this happening? backend error?

File: frontend/app/src/store/blockchain/accounts/index.ts [hunk 18]
```diff
@@ -47,40 +47,33 @@ export const useBlockchainAccountsStore = defineStore(
...
-          xpub,
-          tags
-        });
+      const { taskId } = await addBlockchainAccount({
+        blockchain,
+        address,
+        label,
+        xpub,
+        tags
+      });
```
Comment (kelsos) [inline frontend/app/src/store/blockchain/accounts/index.ts:56]: Was some error suppressed by the try catch?

File: frontend/app/src/store/blockchain/index.ts [hunk 19]
```diff
@@ -113,10 +114,11 @@ export const useBlockchainStore = defineStore('blockchain', () => {
       return;
     }
 
+    const addr = await Promise.all(
+      payload.map(data => addAccount(blockchain, data))
+    );
```
Comment (kelsos) [inline frontend/app/src/store/blockchain/index.ts:119]: Any specific reason this is now out of the try catch?

File: frontend/app/src/components/profitloss/ReportMissingPrices.vue [hunk 20]
```diff
@@ -101,6 +140,10 @@ export default defineComponent({
       await fetchHistoricalPrices();
     });
 
+    const refreshedHistoricalPrices: Ref<{ [key: string]: BigNumber }> = ref(
```
Comment (kelsos) [inline frontend/app/src/components/profitloss/ReportMissingPrices.vue:143]: nitpick: Record<string, BigNumber> in general I think it makes more sense to use TS standard library when possible

File: frontend/app/src/store/blockchain/index.ts (hunk 19 above)
Comment (lukicenturi) [reply frontend/app/src/store/blockchain/index.ts:119]: So what I bring out from the catch is the one that register the address.
Sometime this address is typo for example (yabir.ett). If we put this inside this try, it will use the catch below which is open the dialog. But if I bring it out, it will trigger the catch from `<AccountForm>` instead, that show the error exactly below the address field. This is behaviour I wanted. 

Hdyt, how to make it better?

**Review by kelsos — COMMENTED** [review]
I will have a look again later today or tomorrow morning, I have to go out right now.

I only have a small request I know it is not always possible, but if we have a bunch of features and a bunch of fixes I would prefer to have them split into smaller PRs so that I can easily review them.

If you need work from a previous PR maybe you can just base the new PR on the previous for ease and I can review them one by one.

The bigger the PR the harder to review, and also when we rebase a big PR and push on top it's really hard for me to keep track of what I already reviewed and what are new changes.

File: frontend/app/src/components/history/transactions/TransactionContent.vue (hunk 8 above)
Comment (lukicenturi) [reply frontend/app/src/components/history/transactions/TransactionContent.vue:83]: Actually I removed the mobile view for this table, because it was too chaotic with default mobile view from vuetify.

File: frontend/app/src/store/assets/retrieval.ts (hunk 16 above)
Comment (lukicenturi) [reply frontend/app/src/store/assets/retrieval.ts:46]: this happen as fallback if we pass unknown identifier to <amount-display>, for example we set asset="Gwei", it will show "Gwei" in the <amount-display>

File: frontend/app/src/components/history/transactions/TransactionContent.vue (hunk 8 above)
Comment (lukicenturi) [reply frontend/app/src/components/history/transactions/TransactionContent.vue:83]: But I think it's better to not remove it, in case we will work on the mobile view of this table.

File: frontend/app/src/store/blockchain/index.ts (hunk 19 above)
Comment (kelsos) [reply frontend/app/src/store/blockchain/index.ts:120]: This works when you add one address well, but we also have the multi-address addition. What happens if only one out of five addresses is wrong?

File: frontend/app/src/store/assets/asset-cache.ts (hunk 17 above)
Comment (kelsos) [reply frontend/app/src/store/assets/asset-cache.ts:71]: Do you have an example response? or something

File: frontend/app/src/store/assets/retrieval.ts (hunk 16 above)
Comment (kelsos) [reply frontend/app/src/store/assets/retrieval.ts:46]: Maybe keep it empty string and thing of another approach for this the `Gwei` scenario?

File: frontend/app/src/components/price-manager/latest/LatestPriceTable.vue (hunk 10 above)
Comment (kelsos) [reply frontend/app/src/components/price-manager/latest/LatestPriceTable.vue:208]: ok I will check it thanks.

File: frontend/app/package.json [hunk 21]
```diff
@@ -60,7 +60,7 @@
   },
   "devDependencies": {
     "@intlify/eslint-plugin-vue-i18n": "2.0.0",
-    "@mdi/font": "7.0.96",
+    "@mdi/font": "6.9.96",
```
[the remark this answers is not in the document]
Comment (kelsos) [reply frontend/app/package.json:63]: Maybe we can keep the version to the latest and follow this comment? https://github.com/Templarian/MaterialDesign/issues/6564#issuecomment-1110489515

File: frontend/app/src/components/accounts/AccountBalanceTable.vue (hunk 4 above)
Comment (kelsos) [reply frontend/app/src/components/accounts/AccountBalanceTable.vue:613]: Ok so we didn't expose it and we accidentally removed the function right?

File: frontend/app/src/components/PinnedSidebar.vue [hunk 22]
```diff
@@ -28,6 +36,15 @@ const visibleUpdate = (visible: boolean) => {
...
 const { pinned } = storeToRefs(useAreaVisibilityStore());
+
+const component: ComputedRef<any> = computed(() => {
+  const pinnedValue = get(pinned);
+  if (pinnedValue) {
+    if (pinnedValue.name === 'report-actionable-card')
+      return ReportActionableCard;
+  }
+  return null;
+});
```
[the remark this answers is not in the document]
Comment (kelsos) [reply frontend/app/src/components/PinnedSidebar.vue:45]: Ok let me think a bit on that

File: frontend/app/src/components/history/transactions/TransactionContent.vue (hunk 8 above)
Comment (kelsos) [reply frontend/app/src/components/history/transactions/TransactionContent.vue]: Yes, can you improve it instead of removing it? I can think at least of one user that is using rotki on mobile, they might be more.

File: frontend/app/src/locales/en.json (hunk 14 above)
Comment (kelsos) [reply frontend/app/src/locales/en.json]: Yes const makes more sense since way will never be translated

File: frontend/app/src/components/price-manager/latest/LatestPriceTable.vue (hunk 10 above)
Comment (lukicenturi) [reply frontend/app/src/components/price-manager/latest/LatestPriceTable.vue:208]: Keep in mind that the prices still wrong, @prettyirrelevant still fixing the prices

File: frontend/app/package.json (hunk 21 above)
[the remark this answers is not in the document]
Comment (lukicenturi) [reply frontend/app/package.json:63]: I think I'll just go with custom svg instead

File: frontend/app/src/store/assets/asset-cache.ts (hunk 17 above)
Comment (lukicenturi) [reply frontend/app/src/store/assets/asset-cache.ts:71]: Got this 
```
data: {
  message: "One or more of the given identifiers could not be found in the database"
  result: null
}
```

File: frontend/app/src/components/history/transactions/TransactionContent.vue (hunk 8 above)
Comment (lukicenturi) [reply frontend/app/src/components/history/transactions/TransactionContent.vue]: Updated

File: frontend/app/src/store/blockchain/index.ts [hunk 23]
```diff
@@ -113,46 +113,87 @@ export const useBlockchainStore = defineStore('blockchain', () => {
...
+      if (promiseResult[0].status === 'rejected') {
+        throw promiseResult[0].reason;
       }
-      resetDefi();
-      resetDefiStatus();
-      if (blockchain === Blockchain.ETH) {
-        await fetchDetected(filteredAddresses);
+    }
+
+    promiseResult.forEach((res, index) => {
```
Comment (kelsos) [inline frontend/app/src/store/blockchain/index.ts:129]: I will merge as it is but do you think it is possible to add some tests fo this flow after that?

**Review by kelsos — APPROVED** [review]
I am merging, so you can test with these changes, some of the comments I left, that are unresolved I will check after returning.
