### PR TITLE
fix(11396): loading indicator for asset whitelist

### LINKED ISSUE #11396: When adding a token to the white list, the UI freezees
## Problem Definition

When adding a token to the whitelist, the UI freezees, what makes the user wanna also take it out the of "Ignore Asset" Switch, but when that switch is clicked, nothing happens  

Image

and after a while the user is asked to ignoe the asset that was ignered acording to the swich:

Image

The UI after the "add a token to the whitelist" should show a loader, so the user will not be able to do futher actions untill the swtich is updated to a new state.

### System Description

Rotki version: Docker latest (1.41.3)

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #11396 

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/docs/blob/main/usage-guides/index.md) to reflect the changes.

### CODE REVIEW

File: frontend/app/src/pages/assets/[identifier].vue [hunk 1]
```diff
@@ -250,32 +272,18 @@ async function toggleWhitelistAsset() {
...
-            </template>
-            {{ t('ignore.spam.hint') }}
-          </RuiTooltip>
+          <ManagedAssetIgnoreSwitch
+            :identifier="identifier"
+            :is-spam="isSpam"
+            :show-more-options="asset?.assetType === EVM_TOKEN"
+            :loading-ignore="loadingIgnore"
+            :loading-whitelist="loadingWhitelist"
+            :loading-spam="loadingSpam"
```
Comment (kelsos) [inline frontend/app/src/pages/assets/[identifier].vue]: do you think we can reduce the amount of properties passed?

File: frontend/app/src/composables/asset-manager/use-managed-asset-operations.ts [hunk 2]
```diff
@@ -40,40 +43,62 @@ export function useManagedAssetOperations(
 
   const isSpamAsset = (asset: SupportedAsset): boolean => asset.protocol === 'spam';
 
+  const loadingIgnore = ref<string | null>(null);
+  const loadingWhitelist = ref<string | null>(null);
+  const loadingSpam = ref<string | null>(null);
```
Comment (kelsos) [inline frontend/app/src/composables/asset-manager/use-managed-asset-operations.ts]: why | null instead of | undefined?

File: frontend/app/src/composables/asset-manager/use-managed-asset-operations.ts [hunk 3]
```diff
@@ -40,40 +43,62 @@ export function useManagedAssetOperations(
...
   }
 
   const toggleIgnoreAsset = async (asset: SupportedAsset): Promise<void> => {
     const { identifier, name, symbol } = asset;
-    if (get(useIsAssetIgnored(identifier))) {
-      await unignoreAsset(identifier);
-      refreshAssetsConditionally();
+    set(loadingIgnore, identifier);
+    try {
+      if (get(useIsAssetIgnored(identifier))) {
```
Comment (kelsos) [inline frontend/app/src/composables/asset-manager/use-managed-asset-operations.ts]: don't we have a function to do that does not return a Computed?

File: frontend/app/src/composables/asset-manager/use-managed-asset-operations.ts [hunk 4]
```diff
@@ -40,40 +43,62 @@ export function useManagedAssetOperations(
...
   };
 
   const toggleWhitelistAsset = async (identifier: string): Promise<void> => {
-    if (get(isAssetWhitelisted(identifier)))
-      await unWhitelistAsset(identifier);
-    else
-      await whitelistAsset(identifier);
+    set(loadingWhitelist, identifier);
+    try {
+      if (get(isAssetWhitelisted(identifier)))
```
Comment (kelsos) [inline frontend/app/src/composables/asset-manager/use-managed-asset-operations.ts]: also here use the function without the computed

Comment (kelsos) [reply frontend/app/src/composables/asset-manager/use-managed-asset-operations.ts]: I know it's not part of the PR but we could do the same for massIgnore and also use the `refreshAssetsConditionally() in massIgnore (line 131)`
