### PR TITLE
fix: hide amount tooltips in private mode

### LINKED ISSUE #8990: blank tooltip in private mode
## Problem Definition

In private or semi-private mode, when I go to `Accounts & Balances / Blockchain Balances`, expand ETH, and hover the mouse over one of the asset icons in the expanded table (i.e. ETH or WETH icons), it shows 

1. a blank grey tooltip
2. a separate white-on-black tooltip saying "Blockchain Balances per asset" (now tracked separately in #8992)

image

Clearly neither of these are useful, and I don't think either should appear.  To avoid overlap between issues, this issue could focus on the former, whereas #8992 covers the latter.

## Logs

Available on request if needed

### System Description

Operating system: openSUSE Tumbleweed Linux
Rotki version: v1.36.1 AppImage

### PR DESCRIPTION
**Pull request by cleanerzkp**
Closes #8990

### CODE REVIEW

File: frontend/app/src/components/display/amount/AmountDisplay.vue [hunk 1]
```diff
@@ -368,6 +369,7 @@ const [DefineSymbol, ReuseSymbol] = createReusableTemplate<{ name: string }>();
         />
 
         <CopyTooltip
+          :disabled="privacyMode === PrivacyMode.PRIVATE"
```
Comment (lukicenturi) [inline frontend/app/src/components/display/amount/AmountDisplay.vue:372]: you can use `shouldShowAmount` from `const { shouldShowAmount } = storeToRefs(useSessionSettingsStore());`

equivalent to `privacyMode === PrivacyMode.PRIVATE`

File: frontend/app/src/components/accounts/IconTokenDisplay.vue [hunk 2]
```diff
@@ -15,6 +16,7 @@ const props = withDefaults(defineProps<{
 });
 
 const { assets, visible } = toRefs(props);
+const { privacyMode } = storeToRefs(useSessionSettingsStore());
```
Comment (lukicenturi) [inline frontend/app/src/components/accounts/IconTokenDisplay.vue:19]: same for this

**Review by lukicenturi — APPROVED** [review]
LGTM!
