### PR TITLE
Reduces flakiness on integration tests

### LINKED ISSUE #906: Flaky frontend integration tests in the CI due to created user already existing
## Problem Definition

Problem is shown well in this run: https://github.com/rotki/rotki/pull/905/checks?check_run_id=604648744

Below is a gif of the video of the run that failed
ezgif com-video-to-gif

It can easily be seen that the randomly created user for the test already exists so the login step fails. This should not have happened.

Perhaps some sort of caching?

## Task

Solve it and make sure these tests are no longer flaky

### PR DESCRIPTION
**Pull request by kelsos**
Closes #906

### CODE REVIEW

File: electron-app/src/views/OtcTrades.vue [hunk 1]
```diff
@@ -182,11 +182,6 @@ export default class OtcTrades extends Vue {
     this.$api
       .deleteExternalTrade(this.deleteId)
       .then(() => {
-        this.$store.commit('setMessage', {
```
Comment (LefterisJP) [inline electron-app/src/views/OtcTrades.vue:185]: This is what you asked for in the chat I guess? We still get the visual confirmation, for this,right?

Comment (kelsos) [reply electron-app/src/views/OtcTrades.vue:185]: Well the list updates, so this would be enough visual confirmation right? You delete an entry and it disappears.

Comment (LefterisJP) [reply electron-app/src/views/OtcTrades.vue:185]: If the list updates and you are looking at it in the moment it updates I guess yes. The trade can't be in another page, since you are the one deleting/editing it so probably works
