### PR TITLE
fix: disable premium sync pull button when there is upload error

### LINKED ISSUE #7489: Disable premium sync  the pull button when there is an upload error.
## Problem Definition

image

It is unclear that the action that the user should perform is push. 
Make sure that the pull button is disabled and maybe if it makes sense also change the button from outlined to default when the alert is visible.

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #7489
## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

### CODE REVIEW

File: frontend/app/src/components/status/sync/SyncIndicator.vue [hunk 1]
```diff
@@ -50,15 +50,8 @@ const icon = computed(() => {
   return tick ? 'upload-cloud-2-line' : 'upload-cloud-line';
 });
 
-const showAutoUploadOffWarning = computed<boolean>(() => {
-  if (!isDefined(uploadStatus))
-    return false;
-
-  return !get(uploadStatus).uploaded;
-});
```
Comment (kelsos) [inline frontend/app/src/components/status/sync/SyncIndicator.vue:58]: there is no chance here that we will get an `uploaded: true` message?

**Review by kelsos — APPROVED** [review]
lgtm
