### PR TITLE
Fixes auto-updater not working due to environment issues

### LINKED ISSUE #4671: Windows updater fails due to EPERM: operation not permitted
## Problem Definition

Windows auto-update fails for users with `EPERM: operation not permitted, mkdir 'C:\Users\runneradmin'`

Now `runneradmin` is the user in the GitHub Actions that builds the application.

This should normally be `%USERPROFILE%` which would dynamically translate to the logged user's account, but it seems that somehow this gets interpolated during the build process and ends up with the `runneradmin` user hard-coded.

This results to the updater trying to download the update in the wrong user directory failing since it doesn't have permission to do so.

## Logs

```
2022-08-09T08:52:20.909Z: (info): Found version 1.25.1 (url: rotki-win32_x64-v1.25.1.exe)
2022-08-09T08:52:21.841Z: (info): Downloading update from rotki-win32_x64-v1.25.1.exe
2022-08-09T08:52:21.843Z: (debug): updater cache dir: C:\Users\runneradmin\AppData\Local\rotki-updater
2022-08-09T08:52:21.845Z: (error): Error: Error: EPERM: operation not permitted, mkdir 'C:\Users\runneradmin'
2022-08-09T08:52:21.846Z: Error: EPERM: operation not permitted, mkdir 'C:\Users\runneradmin'
```

### System Description

Operating system: Windows (Any)
Rotki version: v1.25.x

### PR DESCRIPTION
**Pull request by kelsos**
Closes #4671

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.

The binaries from this [run](https://github.com/rotki/rotki/actions/runs/2862238386) fake downgrade the version to force the updater popup

## Checks

- [x] macOS 
- [x] Linux
- [x] Windows

### CODE REVIEW

**Comment by kelsos** [comment]
I still need to do some checks before merging this

File: frontend/app/src/background.ts [hunk 1]
```diff
@@ -161,7 +162,7 @@ async function createWindow() {
     pyHandler.setCorsURL(import.meta.env.VITE_DEV_SERVER_URL as string);
     // Load the url of the dev server if in development mode
     await win.loadURL(import.meta.env.VITE_DEV_SERVER_URL as string);
-    if (!process.env.IS_TEST) win.webContents.openDevTools();
+    win.webContents.openDevTools();
```
Comment (kelsos) [inline frontend/app/src/background.ts:165]: I am pretty sure this checks are leftovers from when we where using spectron.

**Review by lukicenturi — APPROVED** [review]
LGTM
