### PR TITLE
Fixes xpub type selection not being respected when prefix is detected

### LINKED ISSUE #1678: If the prefix in the xpub address is different in the the type selected then send the type selected instead
## Problem Definition

Frontend currently will ignore any change of xpub type if when sending the xpub if the key is prefixed with x/y/zpub.
This is a bug and it should not happen. 

### Task
- [x] Send the correct prefix depeding on the selection

### PR DESCRIPTION
**Pull request by kelsos**
Closes #1678

### CODE REVIEW

File: frontend/app/src/components/accounts/AccountForm.vue [hunk 1]
```diff
@@ -399,12 +399,11 @@ export default class AccountForm extends Vue {
   payload(): BlockchainAccountPayload {
     let xpubPayload: XpubPayload | undefined;
     if (this.isBtc && this.isXpub) {
-      const xpubKey = this.xpub.trim();
-      const xpub = AccountForm.isPrefixed(xpubKey)
-        ? xpubKey
-        : `${this.xpubKeyType}${xpubKey}`;
+      const trimmedKey = this.xpub.trim();
```
Comment (LefterisJP) [inline frontend/app/src/components/accounts/AccountForm.vue:402]: So just to make sure I understand what this does.

If I add an `xpub3XDSADSADSADSADSADSADADASDSA` as WPKH then this will change it to `zpub3XDSADSADSADSADSADSADADASDSA` ?

Comment (kelsos) [reply frontend/app/src/components/accounts/AccountForm.vue:402]: yup :)

Comment (LefterisJP) [reply frontend/app/src/components/accounts/AccountForm.vue:402]: But the copy paste auto-detection still works?

Comment (kelsos) [reply frontend/app/src/components/accounts/AccountForm.vue:402]: yup, when you paste it should change to what is inferred

Comment (LefterisJP) [reply frontend/app/src/components/accounts/AccountForm.vue:402]: Okay then should be what I asked. But still not 100% sure this is what the users would need. We would need more feedback for the various types of wallets and xpubs. Still this should go in now.

**Review by LefterisJP — APPROVED** [review]
