### PR TITLE
Fixes price fetch on new account and scientific notation parsing

### LINKED ISSUE #2200: Adding a new account that contains a new asset does not update dashboard price
## Problem Definition

Hey @kelsos this is a minor issue we can fix before the release.

To reproduce, have a normal rotki account with some assets. Then add a new ethereum account that will add a new token to the dashboard. All will be show fine as before, except the Price column will be shown as "-".

## Task

At account addition make sure the price column is populated

### PR DESCRIPTION
**Pull request by kelsos**
Closes #2200

### CODE REVIEW

File: frontend/app/src/services/axios-tranformers.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { AxiosTransformer } from 'axios';
 import { default as BigNumber } from 'bignumber.js';
 
-const isNumber = /^-?\d+(\.\d+)?(E-\d{0,2})?$/;
+const isNumber = /^-?\d+(\.\d+)?((\d(.\d+)?)?[Ee][-+]\d+)?$/;
```
Comment (LefterisJP) [inline frontend/app/src/services/axios-tranformers.ts:4]: regular_expressions

**Review by LefterisJP — APPROVED** [review]
LGTM :) Thanks
