### PR TITLE
fix: fix error related to the exchanges addition and data about them

### LINKED ISSUE #3862: Error related to the exchanges additions and data about them
## Description

When adding a new exchange or information about the exchange location is purged the frontend queries the backend for trades and deposit/withdrawals with the argument only_cache=true. This makes the UI show nothing to the user

## How to reproduce

1.1 Add a new exchange with an API key and go to the trades section. It shows empty
1.2 If you query the same endpoint that the UI queries but with only_cache=false and refresh the trades all the information will be there

The same happens when you purge information for an exchange

## Further notes

I haven't tested if this happens when you delete and exchange but I believe the backend will return no information and the frontend will show nothing as expected

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #3862

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- [ ] Fix error related to the exchanges addition and purging and data related to them

### CODE REVIEW

File: frontend/app/src/store/history/actions.ts [hunk 1]
```diff
@@ -391,6 +422,23 @@ export const actions: ActionTree<HistoryState, RotkehlchenState> = {
...
+    { commit },
+    location: SupportedExchange
+  ): Promise<void> {
+    commit(HistoryMutations.ADD_MOVEMENT_LOCATION_TO_PURGE, location);
+    const params = {
+      location,
+      limit: 1,
+      offset: 0,
+      ascending: false,
+      orderByAttribute: 'time'
```
Comment (yabirgb) [inline frontend/app/src/store/history/actions.ts:435]: Question: Isn't the sort field preserved when navigating between tabs? Is the sort by time here a problem?

Comment (kelsos) [reply frontend/app/src/store/history/actions.ts:435]: These defaults are only for when the parameters are missing from the action.

The pagination event from the table will override these values.
Essentially these defaults are used only for refresh, where the result is ignored by the frontend, since the frontend is now using the `only_cache: true` (db) as a single source of truth.

File: frontend/app/tests/e2e/pages/defi-page.ts [hunk 2]
```diff
@@ -19,9 +19,14 @@ export class DefiPage {
         continue;
       }
 
-      cy.get(`#defi-module-${module}`).scrollIntoView();
-      cy.get(`#defi-module-${module}`).find('button').click();
-      cy.get(`#defi-module-${module}`).should('not.exist');
+      const moduleId = `#defi-module-${module}`;
+      cy.get('body').then($body => {
+        if ($body.find(moduleId).length > 0) {
+          cy.get(moduleId).scrollIntoView();
```
Comment (kelsos) [inline frontend/app/tests/e2e/pages/defi-page.ts:25]: The same comment as the other PR applies here.

**Comment by yabirgb** [comment]
So @lukicenturi I found and issue. For the setup I have already a kraken exchange instance and tried to add a FTX one. Added the exchange and navigated to trades. Then I see two queries to the same endpoint with the same parameters

image

And both query with `only_cache=true`

File: frontend/app/src/store/history/mutations.ts [hunk 3]
```diff
@@ -27,13 +27,64 @@ export const mutations: MutationTree<HistoryState> = {
...
+    }
+
+    const locations = [...state.tradeLocationsToPurge];
+    const locationIndex = locations.indexOf(location);
+    if (locationIndex > -1) {
+      locations.splice(locationIndex, 1);
+      state.tradeLocationsToPurge = [...locations];
+    }
+  },
+
```
Comment (kelsos) [inline frontend/app/src/store/history/mutations.ts:53]: Wouldn't it be simpler to just trigger an `onlyCache: false` trade fetch when adding an exchange?

File: frontend/app/tests/e2e/pages/history-page/ledger-action-page.ts [hunk 4]
```diff
@@ -20,6 +20,7 @@ export class LedgerActionPage {
     return () => {
       // Wait for response.status to be 200
       cy.wait('@apiCall').its('response.statusCode').should('equal', 200);
+      cy.wait(500);
```
Comment (kelsos) [inline frontend/app/tests/e2e/pages/history-page/ledger-action-page.ts:23]: Is there not any alternative here other that hardcoding wait times?

File: frontend/app/src/store/history/mutations.ts (hunk 3 above)
Comment (lukicenturi) [reply frontend/app/src/store/history/mutations.ts:53]: I thought about that too. But I thought of another scenario. 
If I just trigger `onlyCache: false` for a single exchange when adding an exchange, and then the user open the trade page, which will trigger `onlyCache: true` only, if the `onlyCache: false` before still not loaded, then when the user the open trade page, the data is still not updated. I decided to put it on a state, so if user open the trade page and there are `onlyCache: true` query that aren't done yet, just call it again.

File: frontend/app/src/store/history/state.ts [hunk 5]
```diff
@@ -18,9 +18,12 @@ export const defaultState = (): HistoryState => ({
   ignored: {},
   associatedLocations: [],
   trades: defaultHistoricState<TradeEntry>(),
+  tradeLocationsToPurge: [],
   assetMovements: defaultHistoricState<AssetMovementEntry>(),
+  assetMovementLocationsToPurge: [],
   transactions: defaultHistoricState<EthTransactionEntry>(),
-  ledgerActions: defaultHistoricState<LedgerActionEntry>()
+  ledgerActions: defaultHistoricState<LedgerActionEntry>(),
+  ledgerActionLocationsToPurge: []
```
Comment (kelsos) [inline frontend/app/src/store/history/state.ts:26]: In general, what I had in mind as an approach to this didn't require additions to the state, do you think we can take that approach here?

File: frontend/app/src/store/history/mutations.ts (hunk 3 above)
Comment (lukicenturi) [reply frontend/app/src/store/history/mutations.ts:53]: But maybe it's too much. If you find it unnecessary, I will remove it

File: frontend/app/tests/e2e/pages/history-page/ledger-action-page.ts (hunk 4 above)
Comment (lukicenturi) [reply frontend/app/tests/e2e/pages/history-page/ledger-action-page.ts:23]: I'm not sure, I can't find other easy way for fixing this. The problem is sometimes, the order of flow is like this:
call api -> cypress get some element -> the api changes is refresh whole table -> the previous element that cypress get is gone now.

File: frontend/app/src/store/history/mutations.ts (hunk 3 above)
Comment (kelsos) [reply frontend/app/src/store/history/mutations.ts:53]: Let's remove it, we will re-evaluate the logic there either way

Comment (lukicenturi) [reply frontend/app/src/store/history/mutations.ts]: updated

File: frontend/app/tests/e2e/pages/history-page/ledger-action-page.ts (hunk 4 above)
Comment (lukicenturi) [reply frontend/app/tests/e2e/pages/history-page/ledger-action-page.ts:23]: > So @lukicenturi I found and issue. For the setup I have already a kraken exchange instance and tried to add a FTX one. Added the exchange and navigated to trades. Then I see two queries to the same endpoint with the same parameters
> 
> image
> 
> And both query with `only_cache=true`. They both happen at the same time without me doing anything

Updated @yabirgb, can you try again?

**Comment by lukicenturi** [comment]
> So @lukicenturi I found and issue. For the setup I have already a kraken exchange instance and tried to add a FTX one. Added the exchange and navigated to trades. Then I see two queries to the same endpoint with the same parameters
> 
> image
> 
> And both query with `only_cache=true`. They both happen at the same time without me doing anything

Updated @yabirgb, can you try again?

File: frontend/app/tests/e2e/pages/history-page/ledger-action-page.ts (hunk 4 above)
Comment (lukicenturi) [reply frontend/app/tests/e2e/pages/history-page/ledger-action-page.ts:23]: Can we allow this for now and think the other way later? @yabirgb

**Review by yabirgb — APPROVED** [review]
Related to functionality I approve this PR. If kelsos doesn't have any other comment we can GTM

**Review by kelsos — APPROVED** [review]
lgtm
