### PR TITLE
fix(frontend): OKX user region

### LINKED ISSUE #10552: MyOKX API
## Abstract

Currently european users of OKX can only register with myokx.com. When using the API credentials form myokx in Rotki's OKX exchange it does not work.

## Motivation

It should be addressed as you are in europe, too and I guess there will be many changes like bybit and bybit EU.

## Specification

The link to myokx is just https://my.okx.com/ so nothing too wild. But I have no clue if the API also uses this URL.

### PR DESCRIPTION
**Pull request by lukicenturi**
Frontend part of #10742 
Closes #10552

### CODE REVIEW

File: frontend/app/src/composables/api/balances/exchanges.ts [hunk 1]
```diff
@@ -60,10 +60,15 @@ export function useExchangeApi(): UseExchangeApiReturn {
   const callSetupExchange = async ({ mode, ...payload }: ExchangeFormData): Promise<boolean> => {
     let response: AxiosResponse<ActionResult<boolean>>;
 
+    const newPayload = {
+      ...payload,
+      okxLocation: payload.okxLocation ? payload.okxLocation.toLowerCase() : undefined,
```
Comment (kelsos) [inline frontend/app/src/composables/api/balances/exchanges.ts:65]: Wouldn't that send the okx_location property in the request payload for any exchange? can we make it so that it is only send as a key if it exists?

Comment (lukicenturi) [reply frontend/app/src/composables/api/balances/exchanges.ts:65]: At this part it's fine, because `undefined` will filtered out. But I needed to do more filtering, that I fix in the latest commit.
Can you check again @kelsos

**Review by kelsos — APPROVED** [review]
