### PR TITLE
fix: create periodic app update feature

### LINKED ISSUE #2297: Introduce periodic app version update check in the application
## Abstract

Some users keep long-running app sessions and it is not clear that there is an update, since the application on checks for updates during the login. 

If it is possible do a periodic check for updates, for example, every couple of hours and notify the user in case an update is available.

### Task
- [ ] Add a new frontend settings that allows the user to either disable it or specify  how often in hours the check will run.
- [ ] Perform a check every x hours if this setting is activated (24h default)

### PR DESCRIPTION
**Pull request by lukicenturi**
Closes #2297 #3766

## Checklist

- [ ] The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.
- [x] Create settings for user to determine `version update check frequency` in hours
- [x] Do update check version based on the settings.

### CODE REVIEW

File: frontend/app/src/components/status/UpdateIndicator.vue [hunk 1]
```diff
@@ -10,19 +10,37 @@
...
     ...mapGetters(['updateNeeded'])
   }
 })
 export default class UpdateIndicator extends Vue {
   updateNeeded!: boolean;
   version!: Version;
+  versionUpdateCheckFrequency!: number;
+  refreshInterval: any;
+
+  @Watch('versionUpdateCheckFrequency')
```
Comment (lukicenturi) [inline frontend/app/src/components/status/UpdateIndicator.vue:30]: Replace with this for testing, it should check every 5 seconds, with 50% probability that there are update.
`@Watch('versionUpdateCheckFrequency')
async setVersionUpdateCheckInterval() {
  this.refreshInterval = setInterval(async () => {
    await this.$store.dispatch('version');
  }, 5000);
}`

Comment (lukicenturi) [reply frontend/app/src/components/status/UpdateIndicator.vue:30]: And also for this file `frontend/app/src/store/store.ts`, you can change the `version` action into these:

```
async version({ commit }): Promise<void> {
  const { version, dataDirectory } = await api.info();
  if (Math.random() > 0.5) {
    const mockedVersion: BackendVersion = {
      ourVersion: '10',
      latestVersion: '12',
      downloadUrl: 'https://google.com'
    };
    commit('versions', mockedVersion);
  } else if (version) {
    commit('versions', version);
  }

  commit('dataDirectory', dataDirectory);
},
```

File: frontend/app/src/types/frontend-settings.ts [hunk 2]
```diff
@@ -80,10 +83,16 @@ const RoundingMode = z
 
 export type RoundingMode = z.infer<typeof RoundingMode>;
 
+// TODO: Add validation for max minutes allowed using Constraints.MAX_MINUTES_DELAY
```
Comment (kelsos) [inline frontend/app/src/types/frontend-settings.ts:86]: Is there anything stopping us for doing this at the moment?

Comment (lukicenturi) [reply frontend/app/src/types/frontend-settings.ts:86]: Based on our chat, this will happen if user previously already set higher number before this update released. This is error when zod try to parse user settings 
image

File: frontend/app/src/App.vue [hunk 3]
```diff
@@ -76,7 +76,7 @@
         @visible:update="help = $event"
         @about="showAbout = true"
       />
-      <v-main v-if="logged">
```
Comment (kelsos) [inline frontend/app/src/App.vue:79]: Is there a reason why this check was removed?

Comment (lukicenturi) [reply frontend/app/src/App.vue:79]: This is redundant, already checked at line 4

File: frontend/app/src/types/frontend-settings.ts (hunk 2 above)
Comment (kelsos) [reply frontend/app/src/types/frontend-settings.ts:86]: In this case I think you could use [preprocess](https://github.com/colinhacks/zod#preprocess) to do this check with the constraints. This way you could just force it to max if it bigger than that. Since preprocess runs before the parsing/validation it should solve this.

File: frontend/app/src/App.vue (hunk 3 above)
Comment (kelsos) [reply frontend/app/src/App.vue:79]: Oh, nice catch, thanks. It is always nice to have a second pair of eyes. Sometimes it is really easy to miss stuff.

**Comment by kelsos** [comment]
@lukicenturi, it seems to work fine, thank you.

One change I would like would be to enable it by default, with a 24h period.
Furthermore, it would be nice if we could use zod's preprocess to handle these todos.
Do you think it is possible?

**Comment by lukicenturi** [comment]
> @lukicenturi, it seems to work fine, thank you.
> 
> One change I would like would be to enable it by default, with a 24h period. Furthermore, it would be nice if we could use zod's preprocess to handle these todos. Do you think it is possible?

Yeah I think it's possible, I just didn't familiar with zod before and don't know what it can do, will check it now. Thank you @kelsos

File: frontend/app/src/types/user.ts [hunk 4]
```diff
@@ -15,13 +21,23 @@ const OtherSettings = z.object({
...
+      data[VERSION_UPDATE_CHECK_FREQUENCY] = Constraints.MAX_HOURS_DELAY;
+    }
     return FrontendSettings.parse(data);
   }),
   premiumShouldSync: z.boolean(),
   havePremium: z.boolean()
 });
 
 type OtherSettings = z.infer<typeof OtherSettings>;
+``;
```
Comment (kelsos) [inline frontend/app/src/types/user.ts:40]: I guess this was a typo here?

File: frontend/app/src/types/user.ts [hunk 5]
```diff
@@ -15,13 +21,23 @@ const OtherSettings = z.object({
...
     const data = arg ? axiosCamelCaseTransformer(JSON.parse(arg)) : {};
+    if (data[REFRESH_PERIOD] > Constraints.MAX_MINUTES_DELAY) {
+      data[REFRESH_PERIOD] = Constraints.MAX_MINUTES_DELAY;
+    }
+    if (data[QUERY_PERIOD] > Constraints.MAX_SECONDS_DELAY) {
+      data[QUERY_PERIOD] = Constraints.MAX_SECONDS_DELAY;
+    }
+    if (data[VERSION_UPDATE_CHECK_FREQUENCY] > Constraints.MAX_HOURS_DELAY) {
+      data[VERSION_UPDATE_CHECK_FREQUENCY] = Constraints.MAX_HOURS_DELAY;
+    }
```
Comment (kelsos) [inline frontend/app/src/types/user.ts:32]: Out of curiosity didn't zod's preprocess work for the validation? was there a problem using that approach?

Comment (lukicenturi) [reply frontend/app/src/types/user.ts:32]: I thought preprocess is for another purpose, but after I read it again, it should can be used. Trying it now...

Comment (kelsos) [reply frontend/app/src/types/user.ts:32]: You can also use it for other purposes too, but in general, it is for preprocessing the data before passing it to the parser, which is what we need to do in this case.

Comment (lukicenturi) [reply frontend/app/src/types/user.ts]: This is are achieved using preprocess now @kelsos

**Review by kelsos — APPROVED** [review]
lgtm
