### PR TITLE
Fix defi settings button issue after wizard

### LINKED ISSUE #1320: Defi settings shortcut button problems
## Problem Definition

There are two problems with the DeFi settings shortcut button.

1. The button does not appear after the wizard finishes, if the user has no ethereum accounts
2. The tool-tip is not visible
Peek 2020-08-12 16-04

## Task

Fix it

### PR DESCRIPTION
**Pull request by CPatchane**
Fix #1320 

@LefterisJP On my side the tooltip at the top is correctly above the app bar so it's not cropped like you described in the issue. Do you still want to change it (position? z-index?) or do you want to keep it as it?

### CODE REVIEW

File: frontend/app/src/store/settings/consts.ts [hunk 1]
```diff
@@ -1 +1 @@
-export const DEFI_SETUP_DONE = 'defiSetupDone';
+export const DEFI_SETUP_DONE = 'defiSetupDone' as 'defiSetupDone';
```
Comment (kelsos) [inline frontend/app/src/store/settings/consts.ts:1]: Would it be possible to explain what problem using `as` here solves?

**Comment by LefterisJP** [comment]
> @LefterisJP On my side the tooltip at the top is correctly above the app bar so it's not cropped like you described in the issue. Do you still want to change it (position? z-index?) or do you want to keep it as it?

Funnily enough in this PR and in develop the cropped behaviour I saw in the issue was not a problem. And the PR does solve the problem so I will merge. But please also answer @kelsos question.

File: frontend/app/src/store/settings/consts.ts (hunk 1 above)
Comment (CPatchane) [reply frontend/app/src/store/settings/consts.ts:1]: As far as I understand, it forces typing `DEFI_SETUP_DONE` as a unique symbol `defiSetupDone` instead of a string. Using that allow me to use it as dynamic props in the component class attribute otherwise I get:
Screenshot 2020-08-15 at 01 07 47

Comment (kelsos) [reply frontend/app/src/store/settings/consts.ts:1]: Thank you for the explanation 👍
